services:
  devnet:
    build:
      dockerfile: ./Dockerfile
    environment:
      - FAUCET_PRIVATE_KEY_HEX=323b1d8f4eed5f0da9da93071b034f2dce9d2d22692c172f3cb252a64ddfafd01b057de320297c29ad0c1f589ea216869cf1938d88c9fbd70d6748323dbf2fa7
    ports:
      - "9650:9650"
      - "8765:8765"
    volumes:
      - type: volume
        target: /go/pkg/mod
      - type: volume
        target: /root/.cache/go-build
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9650"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 300s

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - SERVE_DOMAIN

volumes:
  caddy_data:
  caddy_config: